### ISSUE TITLE
Create a pip package

### ISSUE THREAD

**Issue by hugsy** [hypn0s/AJPy#1]
Hey,

First of, great job. 

Could you consider create a `pip` package (and publish it to Pypi) for your library so it can be reused in other tool ? I'm mostly thinking of [`patator`](https://github.com/lanjelot/patator), for which it would not take a lot of effort to integrate and add AJP support.

Cheers

**Comment by hypn0s** [comment]
Hi, thank's!

Sure, I will try to deal with this issue ASAP. I'm also interested in AJP support for patator ;)

**Comment by hypn0s** [comment]
Finally registered: https://pypi.python.org/pypi/ajpy

It's my first pip package, tell me if everything is OK and I will close this issue.

**Comment by hugsy** [comment]
Salut !

Sur une Ubuntu vanilla, testé en 2 min

``` bash
vagrant@vagrant:~$ pip search ajpy
ajpy (0.0.1)  - AJP package crafting library
vagrant@vagrant:~$ pip install ajpy --user
Collecting ajpy
  Could not find a version that satisfies the requirement ajpy (from versions: )
No matching distribution found for ajpy
```

Je vais regarder un peu plus plus tard.

PS: Ah mais t'es chez Synacktiv ! Tu passeras le bonjour à tes chefs ;)
PS bis: bonne doc -> http://python-packaging.readthedocs.io/en/latest/minimal.html

**Comment by hypn0s** [comment]
En fait, j'avais pas uploadé le package oups... Maintenant c'est bon, j'ai pu l'installer et le script de test tomcat.py fonctionne bien ;)

PS : je leur passe le bonjour ;)

**Comment by hugsy** [comment]
Super boulot, je sens que cet lib sera bien utile...

Merci!
