### ISSUE TITLE
Failed to get CSRF token.

### ISSUE THREAD

**Issue by Lpker-2006** [hypn0s/AJPy#10]
this is the command i run in the powershell:
python tomcat.py upload -u admin -p admin Linuxx.war 192.168.0.103

Traceback (most recent call last):
  File "tomcat.py", line 366, in <module>
    bf.upload(args.filename, args.user, args.password, args.old_version, args.headers)
  File "tomcat.py", line 177, in upload
    deploy_csrf_token, obj_cookie = self.get_csrf_token(user, password, old_version, headers)
TypeError: 'NoneType' object is not iterable

**Comment by hypn0s** [comment]
Hi,

Please describe the context, I cannot reproduce without it.

What tomcat version is running? Does the credentials are valid?

**Comment by Lpker-2006** [comment]
> Hi,
> 
> Please describe the context, I cannot reproduce without it.
> 
> What tomcat version is running? Does the credentials are valid?

I am sorry .

Tomcat version：Apache Tomcat / 8.5.45
OS：windows10
credential was set by me so it is right
 '<user username="admin" password="admin" roles="admin, admin-gui, manager-gui"/>'

**Comment by hypn0s** [comment]
Hi,

I managed to reproduce the issue. Indeed I handle not well an error, I will make a commit to fix this.

However, the real issue here is that the manager is accessible only from localhost. Did you check that the manager interface can be accessed from where you ran the script? (The file webapps/manager/META-INF/context.xml must be edited to make the manager app accessible from other locations).

**Comment by Lpker-2006** [comment]
> However, the real issue here is that the manager is accessible only from localhost. Did you check that the manager interface can be accessed from where you ran the script? (The file webapps/manager/META-INF/context.xml must be edited to make the manager app accessible from other locations).

content from the context.xml:

Valve className="org.apache.catalina.valves.RemoteAddrValve"
allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" 

although i cant really understand what it is but i guess it allow any IP to access the manager?
 i am sorry my english is bad  if you dont what i m saying is ok.
after all ,waiting for your commit.

**Comment by hypn0s** [comment]
This line allows connections only from localhost. You can actually check using your browser and HTTP. The behavior is the same.
