### ISSUE TITLE
Submit a bug

### ISSUE THREAD

**Issue by heyzm** [hypn0s/AJPy#11]
Hello, author. I found that you have a problem when the matching version, in the regular match out, I do not know whether your space is intentional or unintentional, through my practice encountered the version does not match the problem, has now been removed fixed.

**Comment by heyzm** [comment]
It should be changed to  "s = re.findall('(Apache Tomcat/[0-9\.]+) ', d.data)",Remove the space sits after the regular expression

**Comment by hypn0s** [comment]
Fixed in https://github.com/hypn0s/AJPy/commit/bd09886e85262360106779b505be2605cfdc9ac0
