### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by dattachandan** [hypn0s/AJPy#14]
Hi Julien

Thanks for the scripts. I am having a few issues while trying to use them, not sure if I am following the right steps.

Did not work code: 
`mymac:AJPy cd$ python tomcat.py version 10.2.2.11 --port 20022
usage: tomcat.py [-h] [--port PORT] [-v]
                 {bf,upload,undeploy,version,list,read_file} ... target
tomcat.py: error: unrecognized arguments: 10.2.2.11 --port`

`mymac:AJPy cd$ python tomcat.py list 10.2.2.11 
Traceback (most recent call last):
  File "tomcat.py", line 355, in <module>
    bf = Tomcat(args.target, args.port)
  File "tomcat.py", line 78, in __init__
    self.socket.connect((target_host, target_port))
ConnectionRefusedError: [Errno 61] Connection refused`

This server was vulnerable but the script came back with no.

`mymac:AJPy chandan$ python tomcat.py version 10.2.2.12
None`

**Comment by hypn0s** [comment]
Hi @dattachandan ,

As I can see from your commands, you don't set the optional argument correctly. The port flag should be set before the IP address:
`python tomcat.py version --port 20022 10.2.2.11`

The same thing applies to the version and list commands. By default, the TCP port 8009 is used.

**Comment by dattachandan** [comment]
Thanks, tried but gives a different error

```

python tomcat.py version --port 20022 10.2.2.11
usage: tomcat.py [-h] [--port PORT] [-v]
                 {bf,upload,undeploy,version,list,read_file} ... target
tomcat.py: error: unrecognized arguments: --port 20022

```

**Comment by hypn0s** [comment]
Sorry, I was completely wrong, as you can see from the provided usage:
```
python tomcat.py --port 20022 version 10.2.2.11
```

argparse sucks with subparsers...

**Comment by dattachandan** [comment]
Thanks, that worked. 

Does this output mean the tomcat is patched without this CVE issue?

```
python tomcat.py  --port 9009 version 10.2.2.173
No data in response. Headers:
 {'data_length': 10,
 'http_status_code': 200,
 'http_status_msg': b'OK',
 'magic': 16706,
 'num_headers': 0,
 'prefix_code': 4,
 'response_headers': {}}
None
```

**Comment by hypn0s** [comment]
This only means the version could not be retrieved, as in not included in the pages.
