### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by 3post** [hypn0s/AJPy#22]
/AJPy/ajpy/ajp.py

kali2020.4
python 2.7.18

`def unpack(stream, fmt):
    print stream, fmt
    size = struct.calcsize(fmt)
    print size
    buf = stream.read(size)
    print buf
    if "" in buf:
        print "error"
    return struct.unpack(fmt, buf)`

`<socket._fileobject object at 0x7f4b45690ad0> >HHb
5

error
Traceback (most recent call last):
  File "tomcat.py", line 378, in <module>
    hdrs, data = bf.perform_request("/" + args.webapp + "/xxxxx.jsp", attributes=attributes)
  File "tomcat.py", line 154, in perform_request
    responses = self.forward_request.send_and_receive(self.socket, self.stream)
  File "。。。。。。。。。。。/AJPy-master/ajpy/ajp.py", line 279, in send_and_receive
    r = AjpResponse.receive(stream)
  File "。。。。。。。。。。。/AJPy-master/ajpy/ajp.py", line 385, in receive
    r.parse(stream)
  File "。。。。。。。。。。。/AJPy-master/ajpy/ajp.py", line 342, in parse
    self.magic, self.data_length, self.prefix_code = unpack(stream, ">HHb")
  File "。。。。。。。。。。。/AJPy-master/ajpy/ajp.py", line 50, in unpack
    return struct.unpack(fmt, buf)
struct.error: unpack requires a string argument of length 5
`

**Comment by penetrater** [comment]
`
def unpack(stream, fmt):
    print stream, fmt
    size = struct.calcsize(fmt)
    print size
    buf = stream.read(size)
    print buf
    if "" in buf:
        print "error"
    return struct.unpack(fmt, buf)
`

**Comment by 3post** [comment]
def unpack(stream, fmt):
    print stream, fmt
    size = struct.calcsize(fmt)
    print size
    buf = stream.read(size)
    print buf
    if "" in buf:
        print "error"
    return struct.unpack(fmt, buf)

**Comment by hypn0s** [comment]
I'm sorry but I don't understand your issue. Please provide more information:
* Have you tested with Python 3?
* Which version of tomcat are you trying to communicate with?
* What is your actual issue? 

You just put some code and stacktrace without any kind of context, I can't help you with so little information.

**Comment by 3post** [comment]
oh, i am not test with python 3. 
Apache Tomcat/Coyote JSP engine 1.1：nmap scan result(it is not my server): Apache Tomcat/Coyote JSP engine 1.1

`
def unpack(stream, fmt):
print stream, fmt
size = struct.calcsize(fmt)
print size
buf = stream.read(size)
print buf
if "" in buf:
print "error"
return struct.unpack(fmt, buf)
`
stream: <socket._fileobject object at 0x7f4b45690ad0>
fmt: >HHb
size: 5
buf: ''ps:empty
buf: it is empty
Now how to modify the code to make it work properly?

**Comment by hypn0s** [comment]
Hi, if you see "Apache Tomcat/Coyote JSP engine 1.1" in your nmap output it means it's an Apache HTTP server with mod_jk loaded so it is not AJP but HTTP. AJP usually is exposed on port 8009 and nmap will tell you 'Apache Jserv (Protocol v1.3)' instead.

AJPy only uses the AJP protocol, not the HTTP which is already supported by, any other web tool I would say.

**Comment by 3post** [comment]
oh, it is all my fault, I thought they were the same.
Thank you very much!
