### ISSUE TITLE
two question about read file

### ISSUE THREAD

**Issue by Gs52jrfnxnPXBGAW** [hypn0s/AJPy#26]
Hello, I have some questions for you.

first:

if I want to read file in ROOT, what should I do?

for example:

a file is D:\ALL\javaidea\apache-tomcat-8.5.50-src\source\webapps\test.txt

Can I read this? I tried a lot, but I couldn't solve it.:(

second: Can I read it in springboot?

also, I tried a lot, but I couldn't solve it.:(

**Comment by hypn0s** [comment]
Hello,

To read files in the ROOT application, just use `--webapp=ROOT` or remove completely the `--webapp` option (not 100% sure).

Regarding the springboot question, I don't really know but if the Tomcat version is affected and the AJP port exposed, it should work. Please note that I did not find the Ghostcat vulnerability, you might reach directly the researchers who found it.
