### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by hlef** [hypn0s/AJPy#8]
Hi Julien,

I am about to package AJPy for Debian, but found out that the license of AJPy isn't well defined. The header in ajp.py looks like a BSD license, but since you didn't include it completely, I can't know if it's a [BSD-2, 3 or 4 clause](https://en.wikipedia.org/wiki/BSD_licenses). Can you clarify this point?

Thanks for your work !

**Comment by hypn0s** [comment]
Hi Hugo,

Thank you for your interest in packaging AJPy. I will try to clarify this ASAP.

**Comment by hypn0s** [comment]
Hi Hugo,

I changed the license header of ajpy/ajpy.py file to BSD-4 license format. Let me know if something is blocking you in the packaging process.

**Comment by hlef** [comment]
Thanks ! However setup.py is still specifying `"License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)"`, which may be somewhat misleading. Is it intentional ?

**Comment by hypn0s** [comment]
My bad, I will change the license in the setup.py tomorrow.

**Comment by hypn0s** [comment]
The license has been updated in setup.py and pushed to pypi.

**Comment by hlef** [comment]
Thanks, I have just uploaded the package to the Debian archive.

**Comment by hypn0s** [comment]
Hi Hugo,

Thank you for the package. However, AJPy only works with python 2.7 currently. I will add the support of python 3 later.

**Comment by hypn0s** [comment]
I just committed a fix to support python 3 (and python 2 compatible). I tested with a custom tomcat.py to make sure all code is covered.

**Comment by hlef** [comment]
Thanks. python-ajpy was just accepted into unstable, and I have uploaded your fix for Python 3 support.

**Comment by hypn0s** [comment]
Thank you Hugo for your work!
